# Generated by Django 5.0 on 2024-04-26 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0001_initial'),
        ('ShoppingCart', '0005_alter_invoicemodel_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('preparing', 'preparing'), ('delivered', 'delivered'), ('canceled', 'canceled')], max_length=50)),
                ('invoice', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='order_invoice', to='ShoppingCart.invoicemodel')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
