# Generated by Django 5.0 on 2024-05-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0003_alter_ordersmodel_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('preparing', 'preparing'), ('delivered', 'delivered')], max_length=50),
        ),
    ]
