# Generated by Django 5.0 on 2024-05-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0004_alter_ordersmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Progressing', 'Progressing'), ('Delivered', 'Delivered')], max_length=50),
        ),
    ]
