# Generated by Django 5.0 on 2024-02-12 17:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backstore', '0009_productmodel_likes_productmodel_sold_counts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='recently_added',
            field=models.BooleanField(default=False),
        ),
    ]
