# Generated by Django 5.0 on 2024-04-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backstore', '0011_productcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='immediate_delivery',
            field=models.BooleanField(default=True),
        ),
    ]
