# Generated by Django 5.0.6 on 2024-05-28 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backstore', '0013_notificationmodel'),
        ('UserManagement', '0002_adminmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='parent',
            field=models.ManyToManyField(blank=True, related_name='children', to='Backstore.categorymodel'),
        ),
        migrations.CreateModel(
            name='DiscountCodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_code', models.CharField(blank=True, max_length=32, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('time_period', models.DurationField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('used', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UserManagement.adminmodel')),
            ],
        ),
    ]
