# Generated by Django 5.0.6 on 2024-05-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backstore', '0014_alter_categorymodel_parent_discountcodemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='numbers',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='tag',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='products', to='Backstore.tagsmodel'),
        ),
    ]
