# Generated by Django 5.0.6 on 2024-06-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backstore', '0016_rename_tag_productmodel_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='slug',
            field=models.SlugField(default='test', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
