# Generated by Django 5.0.6 on 2024-06-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backstore', '0017_productmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
