# Generated by Django 5.0.6 on 2024-06-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backstore', '0022_alter_productmodel_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
