# Generated by Django 5.0.6 on 2024-06-16 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backstore', '0023_productcomment_date_added'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='user',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='user_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
