# Generated by Django 5.0 on 2024-03-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingCart', '0004_invoicemodel_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemodel',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
    ]
