# Generated by Django 5.0 on 2024-04-30 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0003_alter_ordersmodel_invoice'),
        ('ShoppingCart', '0005_alter_invoicemodel_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicemodel',
            name='invoice_products',
        ),
        migrations.RemoveField(
            model_name='invoicemodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='InvoiceItemModel',
        ),
        migrations.DeleteModel(
            name='InvoiceModel',
        ),
    ]
