# Generated by Django 5.0.6 on 2024-06-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingCart', '0009_alter_shoppingcartmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
