# Generated by Django 5.0.6 on 2024-06-20 16:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingCart', '0010_alter_shoppingcartmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
