# Generated by Django 5.0 on 2024-04-25 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PayManagement', '0001_initial'),
        ('ShoppingCart', '0005_alter_invoicemodel_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ShoppingCart.invoicemodel'),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='status',
            field=models.CharField(choices=[('successful', 'Successful'), ('error', 'Error')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
