# Generated by Django 5.0 on 2024-04-26 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PayManagement', '0002_alter_paymentmodel_invoice_alter_paymentmodel_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='invoice',
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='status',
            field=models.CharField(choices=[('successful', 'Successful'), ('error', 'Error'), ('pending', 'Pending')], max_length=50),
        ),
    ]
