# Generated by Django 5.0 on 2024-04-30 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PayManagement', '0003_remove_paymentmodel_invoice_paymentmodel_user_and_more'),
        ('Backstore', '0012_productmodel_immediate_delivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Backstore.productmodel')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('refid', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('invoice_products', models.ManyToManyField(through='PayManagement.InvoiceItemModel', to='Backstore.productmodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='invoiceitemmodel',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PayManagement.invoicemodel'),
        ),
        migrations.DeleteModel(
            name='PaymentModel',
        ),
    ]
