# Generated by Django 5.0.6 on 2024-06-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PayManagement', '0005_rename_unit_price_invoiceitemmodel_price_at_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='anonymous_user_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
