# Generated by Django 5.0 on 2024-02-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductCatalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/product_image'),
        ),
    ]
