# Generated by Django 5.0 on 2024-01-30 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductCatalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='Category',
            field=models.ForeignKey(default='All', on_delete=django.db.models.deletion.SET_DEFAULT, to='ProductCatalog.categorymodel'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='numbers',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='price',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='tag',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
