# Generated by Django 5.0 on 2024-02-02 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductCatalog', '0003_alter_productmodel_discount_alter_productmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='category', to='ProductCatalog.categorymodel'),
        ),
    ]
