# Generated by Django 5.0 on 2024-02-07 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductCatalog', '0005_alter_productmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='categorymodel',
            name='rgt',
        ),
    ]
