# Generated by Django 5.0 on 2024-02-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductCatalog', '0007_categorymodel_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='Category',
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='tag',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='category',
            field=models.ManyToManyField(related_name='category', to='ProductCatalog.categorymodel'),
        ),
    ]
